### ISSUE TITLE
Backward support with old browser

### ISSUE THREAD

**Issue by hoelee** [Zuehlke/springboot-sec-tutor#1]
May I know it is okay to limit TLS 1.0 & TLS 1.1?
I'm noticed current cipher will not work for IE 10 or older and not working for android 4.3 and older... 

Using below:
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

What I'm testing below can get A- from ssllabs, this still less some forward secrecy support for some browser since server no preference choose encryption with forward secrecy support over client in common encryption methods.
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA

I'm don't want constraint some users to access the website with old browser... 
Any possible to set cipher suites according to server preference and still get A+ grade certificated in www.ssllabs.com/ssltest testing?
Appreciate your reply.
Thanks.

**Comment by bgrenacher** [comment]
Hi,
Short answer: No you can't get a A+ at ssllabs if you want to support legacy clients.
It is true that server honors strong ciphers (if configured correctly), but the ciphers are exchanged in plaintext as part of the SSL handshake. This means a MITM can intercept the handshake and therefore enforce the sessions cipher (as long as it is supported by the server and client).
Depending on your security requirements you therefore have to either drop the support for legacy clients or you allow some ciphers with a bigger attack surface (this doesn't necessarily means completely insecure, but will not get you a A+ at ssllabs).
Please also refer to [https://wiki.mozilla.org/Security/Server_Side_TLS](https://wiki.mozilla.org/Security/Server_Side_TLS) for details about the current ciphers. The ssllabs output will also tell you what ciphers of your configuration are problematic (and the ciphers browser support).

Cheers
